package vista;

import controlador.Ctrl_paciente;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JPanel;
import modelo.Usuario;

public final class FrmMenu extends javax.swing.JFrame {

    public FrmMenu() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setTitle("Menú - Hospital de Emergencias");
        this.setSize(new Dimension(1600, 1036));
    }

    private Usuario usuario;

    public FrmMenu(Usuario usuario) {
        initComponents();
        this.usuario = usuario;

        PanelPerfil perfilPanel = new PanelPerfil(usuario);
        mostrarPanel(perfilPanel.getPnlPerfil());
    }

    public int getIdUsuarioLogueado() {
        return usuario.getIdUsuario();
    }

    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/imagen/logoH.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelRound1 = new Componente.PanelRound();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        panelRound2 = new Componente.PanelRound();
        btnCitas = new Componente.ButtonRound();
        btnAgendar = new Componente.ButtonRound();
        btnHistorial = new Componente.ButtonRound();
        btnPrescripciones = new Componente.ButtonRound();
        btnReportes = new Componente.ButtonRound();
        btnCerrrarSesion = new Componente.ButtonRound();
        btnPerfil = new Componente.ButtonRound();
        pnlPrincipal = new Componente.PanelRound();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(203, 216, 227));
        jPanel1.setPreferredSize(new java.awt.Dimension(1500, 900));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRound1.setBackground(new java.awt.Color(242, 242, 242));
        panelRound1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/logoHE.png"))); // NOI18N
        panelRound1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 21)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 102));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Hospital de Emergencias");
        panelRound1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, -1, -1));

        jLabel7.setFont(new java.awt.Font("Yu Gothic Medium", 1, 22)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 51, 102));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("VILLA EL SALVADOR");
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelRound1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 230, -1));

        jPanel1.add(panelRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 360, 120));

        panelRound2.setBackground(new java.awt.Color(242, 242, 242));
        panelRound2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCitas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/calendario.png"))); // NOI18N
        btnCitas.setText("CITAS PROGRAMADAS");
        btnCitas.setColorClick(new java.awt.Color(0, 51, 102));
        btnCitas.setColorFin(new java.awt.Color(47, 114, 181));
        btnCitas.setColorHover(new java.awt.Color(45, 118, 154));
        btnCitas.setColorInicio(new java.awt.Color(47, 114, 181));
        btnCitas.setFont(new java.awt.Font("Verdana", 1, 19)); // NOI18N
        btnCitas.setRound(50);
        btnCitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCitasActionPerformed(evt);
            }
        });
        panelRound2.add(btnCitas, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 320, 60));

        btnAgendar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/agendar.png"))); // NOI18N
        btnAgendar.setText(" AGENDAR CITAS");
        btnAgendar.setColorClick(new java.awt.Color(0, 51, 102));
        btnAgendar.setColorFin(new java.awt.Color(47, 114, 181));
        btnAgendar.setColorHover(new java.awt.Color(45, 118, 154));
        btnAgendar.setColorInicio(new java.awt.Color(47, 114, 181));
        btnAgendar.setFont(new java.awt.Font("Verdana", 1, 19)); // NOI18N
        btnAgendar.setRound(50);
        btnAgendar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgendarActionPerformed(evt);
            }
        });
        panelRound2.add(btnAgendar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 320, 60));

        btnHistorial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/historial.png"))); // NOI18N
        btnHistorial.setText(" HISTORIAL MÉDICO");
        btnHistorial.setColorClick(new java.awt.Color(0, 51, 102));
        btnHistorial.setColorFin(new java.awt.Color(47, 114, 181));
        btnHistorial.setColorHover(new java.awt.Color(45, 118, 154));
        btnHistorial.setColorInicio(new java.awt.Color(47, 114, 181));
        btnHistorial.setFont(new java.awt.Font("Verdana", 1, 19)); // NOI18N
        btnHistorial.setRound(50);
        btnHistorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistorialActionPerformed(evt);
            }
        });
        panelRound2.add(btnHistorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 320, 60));

        btnPrescripciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/prescripcion.png"))); // NOI18N
        btnPrescripciones.setText(" PRESCRIPCIONES");
        btnPrescripciones.setColorClick(new java.awt.Color(0, 51, 102));
        btnPrescripciones.setColorFin(new java.awt.Color(47, 114, 181));
        btnPrescripciones.setColorHover(new java.awt.Color(45, 118, 154));
        btnPrescripciones.setColorInicio(new java.awt.Color(47, 114, 181));
        btnPrescripciones.setFont(new java.awt.Font("Verdana", 1, 19)); // NOI18N
        btnPrescripciones.setRound(50);
        btnPrescripciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrescripcionesActionPerformed(evt);
            }
        });
        panelRound2.add(btnPrescripciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, 320, 60));

        btnReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/reportes.png"))); // NOI18N
        btnReportes.setText(" REPORTES");
        btnReportes.setColorClick(new java.awt.Color(0, 51, 102));
        btnReportes.setColorFin(new java.awt.Color(47, 114, 181));
        btnReportes.setColorHover(new java.awt.Color(45, 118, 154));
        btnReportes.setColorInicio(new java.awt.Color(47, 114, 181));
        btnReportes.setFont(new java.awt.Font("Verdana", 1, 19)); // NOI18N
        btnReportes.setRound(50);
        btnReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportesActionPerformed(evt);
            }
        });
        panelRound2.add(btnReportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 580, 320, 60));

        btnCerrrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/salir.png"))); // NOI18N
        btnCerrrarSesion.setText(" CERRAR SESIÓN");
        btnCerrrarSesion.setColorClick(new java.awt.Color(0, 51, 102));
        btnCerrrarSesion.setColorFin(new java.awt.Color(47, 114, 181));
        btnCerrrarSesion.setColorHover(new java.awt.Color(45, 118, 154));
        btnCerrrarSesion.setColorInicio(new java.awt.Color(47, 114, 181));
        btnCerrrarSesion.setFont(new java.awt.Font("Verdana", 1, 19)); // NOI18N
        btnCerrrarSesion.setRound(50);
        btnCerrrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrrarSesionActionPerformed(evt);
            }
        });
        panelRound2.add(btnCerrrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 690, 320, 60));

        btnPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/usuario.png"))); // NOI18N
        btnPerfil.setText("PERFIL");
        btnPerfil.setColorClick(new java.awt.Color(0, 51, 102));
        btnPerfil.setColorFin(new java.awt.Color(47, 114, 181));
        btnPerfil.setColorHover(new java.awt.Color(45, 118, 154));
        btnPerfil.setColorInicio(new java.awt.Color(47, 114, 181));
        btnPerfil.setFont(new java.awt.Font("Verdana", 1, 30)); // NOI18N
        btnPerfil.setRound(50);
        btnPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerfilActionPerformed(evt);
            }
        });
        panelRound2.add(btnPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 320, 60));

        jPanel1.add(panelRound2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 360, 780));

        pnlPrincipal.setBackground(new java.awt.Color(242, 242, 242));
        pnlPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(pnlPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 30, 1160, 920));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1600, 1000));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerfilActionPerformed
        PanelPerfil pp = new PanelPerfil(this.usuario);
        mostrarPanel(pp.getPnlPerfil());
    }//GEN-LAST:event_btnPerfilActionPerformed

    private void btnCitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCitasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCitasActionPerformed

    private void btnAgendarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgendarActionPerformed
        int idUsuario = getIdUsuarioLogueado();
        PanelAgendar pa = new PanelAgendar(idUsuario);
        mostrarPanel(pa);

    }//GEN-LAST:event_btnAgendarActionPerformed

    private void btnHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistorialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHistorialActionPerformed

    private void btnPrescripcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrescripcionesActionPerformed
        PanelPrescripciones ppr = new PanelPrescripciones();
        mostrarPanel(ppr);
    }//GEN-LAST:event_btnPrescripcionesActionPerformed

    private void btnReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReportesActionPerformed

    private void btnCerrrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrrarSesionActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnCerrrarSesionActionPerformed

    void mostrarPanel(JPanel p) {
        p.setSize(1160, 920);
        p.setLocation(0, 0);

        pnlPrincipal.removeAll();
        pnlPrincipal.add(p, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1160, 920));
        pnlPrincipal.revalidate();
        pnlPrincipal.repaint();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new FrmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Componente.ButtonRound btnAgendar;
    private Componente.ButtonRound btnCerrrarSesion;
    private Componente.ButtonRound btnCitas;
    private Componente.ButtonRound btnHistorial;
    private Componente.ButtonRound btnPerfil;
    private Componente.ButtonRound btnPrescripciones;
    private Componente.ButtonRound btnReportes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private Componente.PanelRound panelRound1;
    private Componente.PanelRound panelRound2;
    private Componente.PanelRound pnlPrincipal;
    // End of variables declaration//GEN-END:variables
}
