/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author zylit
 */
public class FrmMenu extends javax.swing.JFrame {

    /**
     * Creates new form FrmMenu
     */
    public FrmMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelRound1 = new Componente.PanelRound();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        panelRound2 = new Componente.PanelRound();
        btnUsuario1 = new javax.swing.JButton();
        btnUsuario4 = new javax.swing.JButton();
        btnUsuario5 = new javax.swing.JButton();
        btnUsuario6 = new javax.swing.JButton();
        btnUsuario7 = new javax.swing.JButton();
        btnUsuario8 = new javax.swing.JButton();
        btnUsuario9 = new javax.swing.JButton();
        panelRound3 = new Componente.PanelRound();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(203, 216, 227));
        jPanel1.setPreferredSize(new java.awt.Dimension(1500, 900));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRound1.setBackground(new java.awt.Color(242, 242, 242));
        panelRound1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/logoHE.png"))); // NOI18N
        panelRound1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 21)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 102));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Hospital de Emergencias");
        panelRound1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, -1, -1));

        jLabel7.setFont(new java.awt.Font("Yu Gothic Medium", 1, 22)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 51, 102));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("VILLA EL SALVADOR");
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelRound1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 230, -1));

        jPanel1.add(panelRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 360, 120));

        panelRound2.setBackground(new java.awt.Color(242, 242, 242));
        panelRound2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnUsuario1.setBackground(new java.awt.Color(47, 114, 181));
        btnUsuario1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btnUsuario1.setForeground(new java.awt.Color(255, 255, 255));
        btnUsuario1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/calendario.png"))); // NOI18N
        btnUsuario1.setText(" CITAS PROGRAMADAS");
        btnUsuario1.setToolTipText("");
        btnUsuario1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnUsuario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuario1ActionPerformed(evt);
            }
        });
        panelRound2.add(btnUsuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 310, 60));

        btnUsuario4.setBackground(new java.awt.Color(47, 114, 181));
        btnUsuario4.setFont(new java.awt.Font("Verdana", 1, 30)); // NOI18N
        btnUsuario4.setForeground(new java.awt.Color(255, 255, 255));
        btnUsuario4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/usuario.png"))); // NOI18N
        btnUsuario4.setText(" PERFIL");
        btnUsuario4.setToolTipText("");
        btnUsuario4.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnUsuario4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuario4ActionPerformed(evt);
            }
        });
        panelRound2.add(btnUsuario4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 310, 60));

        btnUsuario5.setBackground(new java.awt.Color(47, 114, 181));
        btnUsuario5.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btnUsuario5.setForeground(new java.awt.Color(255, 255, 255));
        btnUsuario5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/salir.png"))); // NOI18N
        btnUsuario5.setText(" CERRAR SESIÓN");
        btnUsuario5.setToolTipText("");
        btnUsuario5.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnUsuario5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuario5ActionPerformed(evt);
            }
        });
        panelRound2.add(btnUsuario5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 690, 310, 60));

        btnUsuario6.setBackground(new java.awt.Color(47, 114, 181));
        btnUsuario6.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btnUsuario6.setForeground(new java.awt.Color(255, 255, 255));
        btnUsuario6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/agendar.png"))); // NOI18N
        btnUsuario6.setText(" AGENDAR CITA");
        btnUsuario6.setToolTipText("");
        btnUsuario6.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnUsuario6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuario6ActionPerformed(evt);
            }
        });
        panelRound2.add(btnUsuario6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 310, 60));

        btnUsuario7.setBackground(new java.awt.Color(47, 114, 181));
        btnUsuario7.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btnUsuario7.setForeground(new java.awt.Color(255, 255, 255));
        btnUsuario7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/historial.png"))); // NOI18N
        btnUsuario7.setText(" HISTORIAL MÉDICO");
        btnUsuario7.setToolTipText("");
        btnUsuario7.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnUsuario7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuario7ActionPerformed(evt);
            }
        });
        panelRound2.add(btnUsuario7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 310, 60));

        btnUsuario8.setBackground(new java.awt.Color(47, 114, 181));
        btnUsuario8.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btnUsuario8.setForeground(new java.awt.Color(255, 255, 255));
        btnUsuario8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/prescripcion.png"))); // NOI18N
        btnUsuario8.setText(" PRESCRIPCIONES");
        btnUsuario8.setToolTipText("");
        btnUsuario8.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnUsuario8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuario8ActionPerformed(evt);
            }
        });
        panelRound2.add(btnUsuario8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, 310, 60));

        btnUsuario9.setBackground(new java.awt.Color(47, 114, 181));
        btnUsuario9.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btnUsuario9.setForeground(new java.awt.Color(255, 255, 255));
        btnUsuario9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/reportes.png"))); // NOI18N
        btnUsuario9.setText(" REPORTES");
        btnUsuario9.setToolTipText("");
        btnUsuario9.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnUsuario9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuario9ActionPerformed(evt);
            }
        });
        panelRound2.add(btnUsuario9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 580, 310, 60));

        jPanel1.add(panelRound2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 360, 780));

        panelRound3.setBackground(new java.awt.Color(242, 242, 242));
        panelRound3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(panelRound3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 30, 1160, 920));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1600, 1000));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUsuario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuario1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUsuario1ActionPerformed

    private void btnUsuario4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuario4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUsuario4ActionPerformed

    private void btnUsuario5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuario5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUsuario5ActionPerformed

    private void btnUsuario6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuario6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUsuario6ActionPerformed

    private void btnUsuario7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuario7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUsuario7ActionPerformed

    private void btnUsuario8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuario8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUsuario8ActionPerformed

    private void btnUsuario9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuario9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUsuario9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new FrmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUsuario1;
    private javax.swing.JButton btnUsuario4;
    private javax.swing.JButton btnUsuario5;
    private javax.swing.JButton btnUsuario6;
    private javax.swing.JButton btnUsuario7;
    private javax.swing.JButton btnUsuario8;
    private javax.swing.JButton btnUsuario9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private Componente.PanelRound panelRound1;
    private Componente.PanelRound panelRound2;
    private Componente.PanelRound panelRound3;
    // End of variables declaration//GEN-END:variables
}
