package vista;

import controlador.Ctrl_cita;
import controlador.Ctrl_paciente;
import java.sql.Date;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;
import modelo.Cita;
import modelo.Paciente;

public class PanelAgendar extends javax.swing.JPanel {

    private Ctrl_paciente ctrlPaciente;
    private int idUsuarioLogueado;
    private Ctrl_cita ctrlCita;

    public PanelAgendar() {
        initComponents();
        ctrlPaciente = new Ctrl_paciente();
        ctrlCita = new Ctrl_cita();
        ctrlPaciente = new Ctrl_paciente();
        ctrlCita = new Ctrl_cita();

        spinnerHoraInicio.setModel(new SpinnerDateModel());
        spinnerHoraInicio.setEditor(new JSpinner.DateEditor(spinnerHoraInicio, "HH:mm"));
        spinnerHoraInicio.setValue(new java.util.Date());

    }

    public PanelAgendar(int idUsuarioLogueado) {
        this();
        this.idUsuarioLogueado = idUsuarioLogueado;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlAgendar = new Componente.PanelRound();
        panelCalendario1 = new Componente.PanelCalendario();
        pnlDni = new Componente.PanelRound();
        txtdni = new javax.swing.JTextField();
        pnlDni1 = new Componente.PanelRound();
        txtdni1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        lbldni = new javax.swing.JLabel();
        lblapellido = new javax.swing.JLabel();
        pnlDni2 = new Componente.PanelRound();
        lblhorainicio = new javax.swing.JLabel();
        pnlDni3 = new Componente.PanelRound();
        lblfecha = new javax.swing.JLabel();
        lblnombre = new javax.swing.JLabel();
        btnAgendar = new Componente.ButtonRound();
        btnBuscar = new Componente.ButtonRound();
        spinnerHoraInicio = new javax.swing.JSpinner();
        txtmotivo = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlAgendar.setBackground(new java.awt.Color(242, 242, 242));
        pnlAgendar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnlAgendar.add(panelCalendario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 120, 700, 710));

        pnlDni.setBackground(new java.awt.Color(242, 242, 242));
        pnlDni.setBorderThickness(1);
        pnlDni.setEnabled(false);
        pnlDni.setFocusable(false);
        pnlDni.setRound(15);
        pnlDni.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtdni.setBackground(new java.awt.Color(242, 242, 242));
        txtdni.setToolTipText("");
        txtdni.setBorder(null);
        txtdni.setSelectedTextColor(new java.awt.Color(242, 242, 242));
        pnlDni.add(txtdni, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 5, 350, 40));

        pnlDni1.setBackground(new java.awt.Color(242, 242, 242));
        pnlDni1.setBorderThickness(1);
        pnlDni1.setEnabled(false);
        pnlDni1.setFocusable(false);
        pnlDni1.setRound(15);
        pnlDni1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtdni1.setBackground(new java.awt.Color(242, 242, 242));
        txtdni1.setToolTipText("");
        txtdni1.setBorder(null);
        txtdni1.setSelectedTextColor(new java.awt.Color(242, 242, 242));
        pnlDni1.add(txtdni1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 5, 360, 40));

        pnlDni.add(pnlDni1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 400, 50));

        pnlAgendar.add(pnlDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 390, 50));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("BUSCAR A PACIENTE POR DNI");
        pnlAgendar.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        lbldni.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbldni.setForeground(new java.awt.Color(102, 102, 102));
        lbldni.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbldni.setText("DNI");
        lbldni.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlAgendar.add(lbldni, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 430, 330, -1));

        lblapellido.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblapellido.setForeground(new java.awt.Color(102, 102, 102));
        lblapellido.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblapellido.setText("APELLIDO");
        lblapellido.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlAgendar.add(lblapellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 480, 330, -1));

        pnlDni2.setBackground(new java.awt.Color(242, 242, 242));
        pnlDni2.setBorderThickness(1);
        pnlDni2.setEnabled(false);
        pnlDni2.setFocusable(false);
        pnlDni2.setRound(15);
        pnlDni2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblhorainicio.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblhorainicio.setForeground(new java.awt.Color(102, 102, 102));
        lblhorainicio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblhorainicio.setText("HORA");
        lblhorainicio.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlDni2.add(lblhorainicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 250, 50));

        pnlAgendar.add(pnlDni2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 610, 310, 50));

        pnlDni3.setBackground(new java.awt.Color(242, 242, 242));
        pnlDni3.setBorderThickness(1);
        pnlDni3.setEnabled(false);
        pnlDni3.setFocusable(false);
        pnlDni3.setRound(15);
        pnlDni3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblfecha.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblfecha.setForeground(new java.awt.Color(102, 102, 102));
        lblfecha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblfecha.setText("FECHA");
        lblfecha.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlDni3.add(lblfecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 250, 50));

        pnlAgendar.add(pnlDni3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 680, 310, 50));

        lblnombre.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblnombre.setForeground(new java.awt.Color(102, 102, 102));
        lblnombre.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblnombre.setText("NOMBRE");
        lblnombre.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlAgendar.add(lblnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 530, 330, -1));

        btnAgendar.setText("buttonRound1");
        btnAgendar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgendarActionPerformed(evt);
            }
        });
        pnlAgendar.add(btnAgendar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 780, -1, -1));

        btnBuscar.setText("buttonRound1");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        pnlAgendar.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 360, -1, -1));
        pnlAgendar.add(spinnerHoraInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(314, 790, 130, 80));

        txtmotivo.setText("jTextField1");
        pnlAgendar.add(txtmotivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 510, -1, -1));

        add(pnlAgendar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1160, 920));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String dni = txtdni.getText().trim();
        Paciente paciente = ctrlPaciente.buscarPacientePorDni(txtdni.getText());

        if (paciente != null) {
            lblnombre.setText(paciente.getNombrePaciente());
            lblapellido.setText(paciente.getApellidoPaciente());
            lbldni.setText(paciente.getDniPaciente());
        } else {
            lblnombre.setText("Nombre");
            lblapellido.setText("Apellido");
            lbldni.setText("DNI");
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnAgendarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgendarActionPerformed
        Paciente paciente = ctrlPaciente.buscarPacientePorDni(txtdni.getText().trim());
        if (paciente == null) {
            JOptionPane.showMessageDialog(this, "Paciente no encontrado");
            return;
        }

        // Obtener la fecha seleccionada del calendario
        java.util.Date fechaSeleccionada = panelCalendario1.getSelectedDate();
        if (fechaSeleccionada == null) {
            JOptionPane.showMessageDialog(this, "Por favor seleccione una fecha");
            return;
        }

        // Convertir a LocalDate
        LocalDate localDate = fechaSeleccionada.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();

        // Obtener la hora del spinner
        java.util.Date dateHora = (java.util.Date) spinnerHoraInicio.getValue();
        LocalTime hora = dateHora.toInstant().atZone(ZoneId.systemDefault()).toLocalTime();

        // Validar que la fecha y hora no sean pasadas
        LocalDateTime citaDateTime = LocalDateTime.of(localDate, hora);
        if (citaDateTime.isBefore(LocalDateTime.now())) {
            JOptionPane.showMessageDialog(this, "La fecha y hora no pueden ser pasadas");
            return;
        }

        // Crear la cita
        Cita cita = new Cita();
        cita.setId_paciente(paciente.getIdPaciente());
        cita.setId_usuario(this.idUsuarioLogueado);
        cita.setFecha_cita(java.sql.Date.valueOf(localDate)); // Fecha
        cita.setHora_inicio(hora); // Hora
        cita.setMotivo(txtmotivo.getText());
        cita.setEstado_cita("Pendiente");

        // Registrar la cita
        boolean exito = ctrlCita.registrarCita(cita);
        if (exito) {
            JOptionPane.showMessageDialog(this, "Cita registrada correctamente");
            lblfecha.setText(cita.getFecha_cita().toString());
            lblhorainicio.setText(cita.getHora_inicio().toString());
            lblnombre.setText(paciente.getNombrePaciente());
            lblapellido.setText(paciente.getApellidoPaciente());
            lbldni.setText(paciente.getDniPaciente());
        } else {
            JOptionPane.showMessageDialog(this, "Error al registrar la cita");
        }
    }//GEN-LAST:event_btnAgendarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Componente.ButtonRound btnAgendar;
    private Componente.ButtonRound btnBuscar;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblapellido;
    private javax.swing.JLabel lbldni;
    private javax.swing.JLabel lblfecha;
    private javax.swing.JLabel lblhorainicio;
    private javax.swing.JLabel lblnombre;
    private Componente.PanelCalendario panelCalendario1;
    private Componente.PanelRound pnlAgendar;
    private Componente.PanelRound pnlDni;
    private Componente.PanelRound pnlDni1;
    private Componente.PanelRound pnlDni2;
    private Componente.PanelRound pnlDni3;
    private javax.swing.JSpinner spinnerHoraInicio;
    private javax.swing.JTextField txtdni;
    private javax.swing.JTextField txtdni1;
    private javax.swing.JTextField txtmotivo;
    // End of variables declaration//GEN-END:variables
}
