package vista;

import controlador.Ctrl_usuario;
import javax.swing.JPanel;
import modelo.Usuario;

public class PanelPerfil extends javax.swing.JPanel {

    public PanelPerfil() {
        initComponents();
    }

    public PanelPerfil(Usuario usuario) {
        initComponents();
        mostrarDatosUsuario(usuario);
    }

    public JPanel getPnlPerfil() {
        return pnlPerfil;
    }

    private void mostrarDatosUsuario(Usuario usuario) {
        if (usuario != null) {
            lblnombreusuario.setText(usuario.getNombreUsuario());
            lblapellidousuario.setText(usuario.getApellidoUsuario());
        } else {
            lblnombreusuario.setText("Nombre");
            lblapellidousuario.setText("Apellido");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPerfil = new Componente.PanelRound();
        jLabel9 = new javax.swing.JLabel();
        lblnombreusuario = new javax.swing.JLabel();
        lblapellidousuario = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlPerfil.setBackground(new java.awt.Color(242, 242, 242));
        pnlPerfil.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Yu Gothic UI", 1, 48)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 51, 102));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("BUEN DÍA,");
        jLabel9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlPerfil.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 340, 70));

        lblnombreusuario.setBackground(new java.awt.Color(255, 255, 255));
        lblnombreusuario.setFont(new java.awt.Font("Yu Gothic UI", 1, 36)); // NOI18N
        lblnombreusuario.setForeground(new java.awt.Color(51, 51, 51));
        lblnombreusuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblnombreusuario.setText("nombre");
        lblnombreusuario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlPerfil.add(lblnombreusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 330, -1));

        lblapellidousuario.setBackground(new java.awt.Color(255, 255, 255));
        lblapellidousuario.setFont(new java.awt.Font("Yu Gothic UI", 1, 36)); // NOI18N
        lblapellidousuario.setForeground(new java.awt.Color(51, 51, 51));
        lblapellidousuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblapellidousuario.setText("apellido");
        lblapellidousuario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlPerfil.add(lblapellidousuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, 330, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/perfil.png"))); // NOI18N
        pnlPerfil.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, 410, 360));

        add(pnlPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1160, 920));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblapellidousuario;
    private javax.swing.JLabel lblnombreusuario;
    private Componente.PanelRound pnlPerfil;
    // End of variables declaration//GEN-END:variables
}
