package vista;

import controlador.Ctrl_cita;
import javax.swing.JPanel;
import modelo.Usuario;

public class PanelPerfil extends javax.swing.JPanel {

    public PanelPerfil() {
        initComponents();
    }

    public PanelPerfil(Usuario usuario) {
        initComponents();
        mostrarDatosUsuario(usuario);
    }

    public JPanel getPnlPerfil() {
        return pnlPerfil;
    }

    private void mostrarDatosUsuario(Usuario usuario) {
        if (usuario != null) {
            lblNombreUsuario.setText(usuario.getNombreUsuario());
            lblApellidoUsuario.setText(usuario.getApellidoUsuario());
            lblCorreoUsuario.setText(usuario.getCorreoUsuario());
            lblDniUsuario.setText(usuario.getDniUsuario());
            lblRol.setText(usuario.getRol());
            lblEstadoUsuario.setText(usuario.getEstado());

            if ("Doctor".equals(usuario.getRol())) {
                Ctrl_cita ctrlCita = new Ctrl_cita();
                int totalCitas = ctrlCita.contarCitasPorDoctor(usuario.getIdUsuario());
                lblTotalCitas.setText(String.valueOf(totalCitas));
            }
        } else {
            lblNombreUsuario.setText("Nombre");
            lblApellidoUsuario.setText("Apellido");
            lblCorreoUsuario.setText("Correo");
            lblDniUsuario.setText("DNI");
            lblRol.setText("Rol");
            lblEstadoUsuario.setText("Estado");
            lblTotalCitas.setText("-");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPerfil = new Componente.PanelRound();
        jLabel9 = new javax.swing.JLabel();
        lblNombreUsuario = new javax.swing.JLabel();
        lblApellidoUsuario = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblCorreoUsuario = new javax.swing.JLabel();
        lblTotalCitas = new javax.swing.JLabel();
        lblEstadoUsuario = new javax.swing.JLabel();
        lblDniUsuario = new javax.swing.JLabel();
        lblRol = new javax.swing.JLabel();
        lblRolUsuario2 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlPerfil.setBackground(new java.awt.Color(242, 242, 242));
        pnlPerfil.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Yu Gothic UI", 1, 48)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 51, 102));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("BUEN DÍA,");
        jLabel9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlPerfil.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 340, 70));

        lblNombreUsuario.setBackground(new java.awt.Color(255, 255, 255));
        lblNombreUsuario.setFont(new java.awt.Font("Yu Gothic UI", 1, 36)); // NOI18N
        lblNombreUsuario.setForeground(new java.awt.Color(51, 51, 51));
        lblNombreUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombreUsuario.setText("nombre");
        lblNombreUsuario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlPerfil.add(lblNombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 330, -1));

        lblApellidoUsuario.setBackground(new java.awt.Color(255, 255, 255));
        lblApellidoUsuario.setFont(new java.awt.Font("Yu Gothic UI", 1, 36)); // NOI18N
        lblApellidoUsuario.setForeground(new java.awt.Color(51, 51, 51));
        lblApellidoUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblApellidoUsuario.setText("apellido");
        lblApellidoUsuario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlPerfil.add(lblApellidoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 330, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/perfil.png"))); // NOI18N
        pnlPerfil.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 430, 410, 360));

        lblCorreoUsuario.setBackground(new java.awt.Color(255, 255, 255));
        lblCorreoUsuario.setFont(new java.awt.Font("Yu Gothic UI", 1, 36)); // NOI18N
        lblCorreoUsuario.setForeground(new java.awt.Color(51, 51, 51));
        lblCorreoUsuario.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCorreoUsuario.setText("correo");
        lblCorreoUsuario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlPerfil.add(lblCorreoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 730, 330, -1));

        lblTotalCitas.setBackground(new java.awt.Color(255, 255, 255));
        lblTotalCitas.setFont(new java.awt.Font("Yu Gothic UI", 1, 36)); // NOI18N
        lblTotalCitas.setForeground(new java.awt.Color(51, 51, 51));
        lblTotalCitas.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTotalCitas.setText("-");
        lblTotalCitas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlPerfil.add(lblTotalCitas, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 170, 330, -1));

        lblEstadoUsuario.setBackground(new java.awt.Color(255, 255, 255));
        lblEstadoUsuario.setFont(new java.awt.Font("Yu Gothic UI", 1, 36)); // NOI18N
        lblEstadoUsuario.setForeground(new java.awt.Color(51, 51, 51));
        lblEstadoUsuario.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblEstadoUsuario.setText("estado");
        lblEstadoUsuario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlPerfil.add(lblEstadoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 800, 330, -1));

        lblDniUsuario.setBackground(new java.awt.Color(255, 255, 255));
        lblDniUsuario.setFont(new java.awt.Font("Yu Gothic UI", 1, 36)); // NOI18N
        lblDniUsuario.setForeground(new java.awt.Color(51, 51, 51));
        lblDniUsuario.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDniUsuario.setText("DNI");
        lblDniUsuario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlPerfil.add(lblDniUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 670, 330, -1));

        lblRol.setBackground(new java.awt.Color(255, 255, 255));
        lblRol.setFont(new java.awt.Font("Yu Gothic UI", 1, 36)); // NOI18N
        lblRol.setForeground(new java.awt.Color(51, 51, 51));
        lblRol.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblRol.setText("rol");
        lblRol.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlPerfil.add(lblRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 610, 330, -1));

        lblRolUsuario2.setBackground(new java.awt.Color(255, 255, 255));
        lblRolUsuario2.setFont(new java.awt.Font("Yu Gothic UI", 1, 36)); // NOI18N
        lblRolUsuario2.setForeground(new java.awt.Color(51, 51, 51));
        lblRolUsuario2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblRolUsuario2.setText("CITAS TOTALES");
        lblRolUsuario2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlPerfil.add(lblRolUsuario2, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 100, 330, -1));

        add(pnlPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1160, 920));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblApellidoUsuario;
    private javax.swing.JLabel lblCorreoUsuario;
    private javax.swing.JLabel lblDniUsuario;
    private javax.swing.JLabel lblEstadoUsuario;
    private javax.swing.JLabel lblNombreUsuario;
    private javax.swing.JLabel lblRol;
    private javax.swing.JLabel lblRolUsuario2;
    private javax.swing.JLabel lblTotalCitas;
    private Componente.PanelRound pnlPerfil;
    // End of variables declaration//GEN-END:variables
}
